version: '3'

services:
  # バックエンドをperlにしたい場合はコメントを外す
  # api-app:
  #   build:
  #     context: ./perl-app
  #     dockerfile: Dockerfile
  #   volumes:
  #     - "./perl-app/src:/app"
  #   networks:
  #     - nginx-server

  # バックエンドをnode.jsにしたい場合はコメントを外す
  api-app:
    build:
      context: ./node-app
      dockerfile: Dockerfile
    volumes:
      - "./node-app/src:/app"
    networks:
      - nginx-server

  view-app:
    build:
      context: ./view-app
      dockerfile: Dockerfile
    volumes:
      - "./view-app/src:/usr/share/nginx/view"
    networks:
      - nginx-server

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - view-app
      - api-app
    networks:
      - nginx-server

networks:
  nginx-server:
    driver: bridge